library(magick)

# 1. Define your file paths
# Replace this with the actual path to the PDF file generated by Quarto
pdf_input_path  <- here("diagram/lit_tag_architecture_pdf.pdf")
tiff_output_path <- here("diagram/lit_tag_architecture.tif")

# 2. Read the PDF vector directly at 300 DPI
# (We add [1] to the path to guarantee it pulls only the primary canvas frame)
pdf_vector <- image_read_pdf(pdf_input_path, density = 300)

# 3. Clean up the container layout edges automatically
pdf_trimmed <- image_trim(pdf_vector)

# 4. Scale precisely to PLOS ONE specifications (2250 pixels wide)
figure_scaled <- image_resize(pdf_trimmed, "2250")

# 5. Write your production-ready, unclipped single-page TIFF
image_write(
  image = figure_scaled,
  path = tiff_output_path,
  format = "tiff",
  density = "300x300",
  compression = "LZW"
)

cat("Success! Your 300 DPI TIFF contains your perfectly unclipped diagram.\n")