library(magick)
library(here)

# this script converts the PNG generated by Quarto to a TIFF suitable for publication in PLOS ONE

# 1. Read the raw unclipped PNG generated by Quarto
input_path <- here("diagram/lit_tag_architecture_files/figure-commonmark/mermaid-figure-1.png")
img <- image_read(input_path)

# 2. Scale up to exactly 2250 pixels wide (7.5 inches * 300 DPI)
img_scaled <- image_scale(img, "2250")

# 3. Explicitly override the density attribute using base R syntax
attr(img_scaled, "density") <- "300x300"

# 4. Export directly as a high-quality, LZW-compressed TIFF for PLOS ONE
image_write(
  img_scaled, 
  path = here("diagram/lit_tag_architecture.tiff"), 
  format = "tiff", 
  compression = "LZW"
)

print("Publication figure successfully created in R at 300 DPI!")