library(magick)
library(here)

# 1. Point to the unclipped raw PNG generated by Quarto
png_input_path   <- here("diagram/diagram_files/figure-typst/dot-figure-1.png")
tiff_output_path <- here("diagram/diagram.tif")

# 2. Enforce target width at 300 DPI (7.5 inches = 2250 pixels)
target_width <- 2250

# 3. Read the unclipped PNG source file
raw_png <- image_read(png_input_path)

# 4. Scale to exact width while letting height adjust proportionally
# Leaving the height blank in the geometry string ("2250") tells magick 
# to scale the height automatically without changing the aspect ratio.
figure_final <- image_resize(raw_png, as.character(target_width))

# 5. Optional check: Ensure it doesn't accidentally exceed PLOS ONE's max height
info <- image_info(figure_final)
if (info$height > 2625) {
  warning("The diagram height (", info$height / 300, "\") exceeds the PLOS ONE maximum of 8.75\".")
}

# 6. Write your production-ready, custom-height TIFF
image_write(
  image = figure_final,
  path = tiff_output_path,
  format = "tiff",
  density = "300x300",
  compression = "LZW"
)

# Calculate final physical inches for confirmation
final_width_in  <- info$width / 300
final_height_in <- info$height / 300

cat(sprintf(
  "Success! Your 300 DPI TIFF is exactly %.2f\" wide by %.2f\" high with zero clipping.\n", 
  final_width_in, 
  final_height_in
))