# This script converts a Quarto-generated SVG figure to a PLOS ONE-compliant TIFF file.

# Install the magick package if you don't have it yet:
# install.packages("magick")
library(magick)
library(rsvg)
library(here)

# 1. Define your file paths
# Replace this with the actual path to the SVG file generated by Quarto
svg_input_path  <- here("diagram/lit_tag_architecture_svg_files/figure-commonmark/mermaid-figure-2.svg")
tiff_output_path <- here("diagram/lit_tag_architecture.tif")
# 2. Use rsvg to read the vector data and render it to a raw memory buffer
# This sets the width to exactly 2250 pixels (7.5 inches * 300 DPI) 
# and processes your 10pt text size cleanly without clipping.
raw_bitmap <- rsvg_raw(svg_input_path, width = 2250)

# 3. Hand the raw bitmap data directly over to magick
# This completely bypasses the broken ImageMagick SVG reader!
img <- image_read(raw_bitmap)

# 4. Save your finalized 300 DPI TIFF with LZW compression
image_write(
  image = img,
  path = tiff_output_path,
  format = "tiff",
  density = "300x300",
  compression = "LZW"
)

cat("Success! Your figure has been saved to:", tiff_output_path, "\n")